global:
  resolve_timeout: 30s
  smtp_require_tls: false

route:
  group_by: ['instance', 'severity']
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 5s
  receiver: 'email-me'

# Alerts
  routes:
  - match:
     alertname: Too_much_load
    receiver: email-me
  - match:
     alertname: PostgresqlDown
    receiver: email-me
  - match:
     alertname: PostgresqlExporterError
    receiver: email-me
  - match:
     alertname: PostgresqlTooManyConnections
    receiver: email-me
  - match:
     alertname: PrometheusTargetMissing
    receiver: email-me
  - match:
     alertname: ContainerKilled
    receiver: email-me
  - match:
     alertname: HostOutOfMemory
    receiver: email-me
  - match:
     alertname: HostHighCpuLoad
    receiver: email-me
  - match:
     alertname: TraefikServiceDown
    receiver: email-me
  - match:
     alertname: HostUnusualNetworkThroughputIn
    receiver: email-me
  - match:
     alertname: HostUnusualDiskReadRate
    receiver: email-me
  - match:
     alertname: HostUnusualDiskWriteRate
    receiver: email-me
  - match:
     alertname: HostOutOfDiskSpace
    receiver: email-me

receivers:
  - name: email-me
    email_configs:
    - to: "t.nsa.8000@gmail.com"
      from: "t.nsa.8000@gmail.com"
      smarthost: "smtp.gmail.com:465"
      auth_username: "t.nsa.8000@gmail.com"
      auth_identity: "t.nsa.8000@gmail.com"
      auth_password: "QLxF@x3BM3kjRk!E"
