---
# handlers file for portainer
- name: Copying the Docker-Compose file.
  copy:
    src: docker-compose.yml
    dest: /etc/

- name: docker build repos
  command: docker-compose up --force-recreate -d
  args:
    chdir: /etc/