version: "3"

services:
  express:
    container_name: "api"
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8081:8081"

  front:
    container_name: "app"
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
