# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
global:
  scrape_interval: 10s
  external_labels:
    monitor: 'node'

# Rules and alerts are read from the specified file(s)
rule_files:
  - /etc/prometheus/rules/alerts.yml

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['40.89.165.142:9093'] ## IP Address of the localhost

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['40.89.165.142:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['40.89.167.98:9100'] ## ServicesHostProd01
      - targets: ['40.89.165.142:9100'] ## ServicesHostProd02
      - targets: ['40.89.171.253:9100'] ## WebHostProd 01
      - targets: ['40.89.169.27:9100'] ## WebHostProd 02
      - targets: ['40.89.169.97:9100'] ## WebHostProd 03
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: ['40.89.165.142:8080'] ## IP Address of the localhost
#  - job_name: ‘postgres_exporter’
#    static_configs:
#    - targets: ['IP:9187']
