- git:
    repo: 'http://deploy:8BFWP_Hws2RT3xseyieG@192.168.0.32/root/back-end.git'
    dest: '/var/www/gitlab-deployment/repos/'
    force: yes
    update: yes

- name: run docker
  command: docker-compose up --force-recreate --build -d
  args:
    chdir: /var/www/gitlab-deployment/repos/
