version: "3"

services:
    phoenix:
        image: ${API_VERSION}
        container_name: "api"
        ports:
            - "4000:4000"
        depends_on:
            - db
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        restart: always
        volumes:
            - ./db:/var/lib/postgresql/data
        ports:
            - "5432"
    front:
        image: ${APP_VERSION}
        container_name: "app"
        stdin_open: true
        volumes:
            - "./app:/app"
        ports:
            - "80:80"
