# Base role
- hosts: all
  connection: ssh
  roles:
    - base

# 
 #- hosts: all
 # roles:
 #   - role: cloudalchemy.grafana
 #     vars:
 #       grafana_security:
 #         admin_user: admin
 #         admin_password: enter_your_secure_password


# Database role
- hosts: database
  connection: ssh
  become: yes
  become_user: root
  roles:
    - database

# Web role
- hosts: web
  connection: ssh
  become: yes
  become_user: root
  roles:
    - web

# Docker role
- hosts: docker
  connection: ssh
  become: true
  become_user: root
  roles:
    - docker
#      vars:
#        grafana_security:
#          admin_user: admin
#          admin_password: xG1A7qMYpZ7jlxmpxeSqUA
