- git:
    repo: 'http://gitlabtoken:xxxxxxxx@192.168.0.32/root/front-end.git'
    dest: '/var/www/gitlab-deployment/repos/'
    force: yes
    update: yes

- name: docker build repos
  command: docker-compose up --force-recreate --build -d
  args:
    chdir: /var/www/gitlab-deployment/repos/

- name: docker up nginx
  command: docker-compose up -d
  args:
    chdir: /var/www/gitlab-deployment/repos/nginx-ssl/
