---
version: '3.3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:v2.0.0
#    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
