version: "3.3"
services: 
    web: 
        image: nginx:latest
        restart: always
        volumes:
            - ./public:/var/www/html
            - ./conf.d:/etc/nginx/conf.d
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data:/var/www/certbot
        ports:
            - 80:80
            - 443:443
    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --keep-until-expiring --webroot-path=/var/www/certbot --email debusschere.antoine@outlook.fr --agree-tos --no-eff-email -d nginx.drivescan.site -d www.nginx.drivescan.site
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data:/var/www/certbot
